apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  params:
  - name: git-repo-url
  - name: git-repo-name
  - name: git-revision
    default: master
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: node-web-app-source-$(uid)
      namespace: node-web-project
    spec:
      params:
      - name: url
        value: $(tt.params.git-repo-url)
      - name: revision
        value: $(tt.params.git-revision)
      - name: git-repo-name
        value: $(tt.params.git-repo-name)
      type: git
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: node-web-app-image-$(uid)
      namespace: node-web-project
    spec:
      params:
      - name: url
        value: 'docker.io/pritidesai/web-node-app:latest'
      type: image
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline-run-
      namespace: node-web-project
    spec:
      serviceAccountName: cdcon-app-builder
      pipelineRef:
        name: node-web-app-pipeline
      resources:
      - name: node-web-app-source
        resourceRef:
          name: node-web-app-source-$(uid)
      - name: node-web-app-image
        resourceRef:
          name: node-web-app-image-$(uid)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-name
    value: $(body.repository.name)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  serviceAccountName: cdcon-app-builder
  triggers:
    - name: node-web-app
      bindings:
        - ref: node-web-app-tb
      template:
        ref: node-web-app-tt
---

#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: el-node-web-app
#  namespace: node-web-project
#spec:
#  host: el-node-web-app.apps.roly-ocp43-cluster.roly-ocp.com
#  to:
#    kind: Service
#    name: el-node-web-app-el
#    weight: 100