apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: node-web-project
spec:

  params:
    - name: BUILDER_IMAGE
      type: string
      default: 'quay.io/buildah/stable:v1.11.0'
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile

  resources:
    - name: node-web-app-source
      type: git
    - name: node-web-app-image
      type: image

  tasks:

    - name: build-and-publish-image
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      resources:
        inputs:
          - name: source
            resource: node-web-app-source
        outputs:
          - name: image
            resource: node-web-app-image
      taskSpec:
        params:
          - name: BUILDER_IMAGE
            type: string
            default: 'quay.io/buildah/stable:v1.11.0'
          - name: DOCKERFILE
            type: string
            default: ./Dockerfile
        resources:
          inputs:
            - name: source
              type: git
          outputs:
            - name: image
              type: image
        steps:
          - name: build-app-image-with-kaniko
            image: "gcr.io/kaniko-project/executor:latest"
            command:
              - /kaniko/executor
            args:
              - --dockerfile=$(resources.inputs.source.path)/$(params.DOCKERFILE)
              - --destination=$(resources.outputs.image.url)
              - --context=dir://$(resources.inputs.source.path)/
