apiVersion: v1
kind: Service
metadata:
  name: node-web-app
  namespace: node-web-project
  labels:
    app: node-web-app
spec:
  type: NodePort
  ports:
  - port: 8082
    name: node-web-app
    nodePort: 32426
  selector:
    app: node-web-app