apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  namespace: node-web-project
  labels:
    app: node-web-app
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-web-app
        version: 1.2.3
    spec:
      containers:
      - name: node-web-app
        image: docker.io/pritidesai/web-node-app:latest
        ports:
        - containerPort: 8082
